language: go

sudo: required

os:
    - linux
    - osx

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

install:
  go get github.com/aftership/aftership-sdk-go/v2

script:
  - make test

branches:
  # only:
  #  - master
